export const SESSION_COOKIE_NAME = 'apiflux_session';

const SESSION_DURATION_DAYS = 5;
const HOURS_PER_DAY = 24;
const MINUTES_PER_HOUR = 60;
const SECONDS_PER_MINUTE = 60;
const MILLISECONDS_PER_SECOND = 1000;

export const SESSION_MAX_AGE_SECONDS =
  SESSION_DURATION_DAYS * HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE;

export const SESSION_EXPIRES_IN_MS =
  SESSION_MAX_AGE_SECONDS * MILLISECONDS_PER_SECOND;
